import type { Metadata } from "next";
import CursorEffect from "@/components/ui/cursor/cursorEffect";
import Navbar from "@/layout/navbar/navbar";
import SmoothScrollProvider from "@/components/smooth-scroll/SmoothScrollProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        <SmoothScrollProvider>
        <CursorEffect>
          <Navbar
            logoUrl="/logos/jp-negro.svg"
            colors={["var(--primary-japon)", "var(--secondary-japon)"]}
            accentColor="var(--primary-japon)"
            menuButtonColor="#ffffff"
            openMenuButtonColor="#16181b"
          />
          {children}
        </CursorEffect>
        </SmoothScrollProvider>
      </body>
    </html>
  );
}
